# Generated by Django 4.2.5 on 2023-09-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiringlink',
            name='expire_in_seconds',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='expiringlink',
            name='expiration',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='expiringlink',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
