# Generated by Django 4.2.5 on 2023-09-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0002_expiringlink_expire_in_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringlink',
            name='expire_in_seconds',
            field=models.PositiveIntegerField(),
        ),
    ]
