# Generated by Django 4.2.5 on 2023-09-14 13:02

from django.db import migrations


def insert_tiers(apps, schema_editor):
    Tier = apps.get_model('core', 'Tier')
    # Default Tier
    basic = Tier(
        name='Basic',
        thumbnailHeights=[200],
    )
    premium = Tier(
        name='Premium',
        thumbnailHeights=[200, 400],
        original_link_access=True,
    )
    enterprise = Tier(
        name='Enterprise',
        thumbnailHeights=[200, 400],
        original_link_access=True,
        expiring_link_generation_access=True,
    )

    Tier.objects.bulk_create([basic, premium, enterprise])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_tiers),
    ]
